algoritmo "Lab - Exerc 4"
// Função : Dado o salário atual do funcionário, some 25% para encontrar o novo salario
// Autor : Ruth Ellen
// Data : 27/10/2020

// Seção de Declarações
var
   s, ns: real

inicio
// Seção de Comandos
escreva ("digite o salario: ")
leia (s)

// Calculo do valor final - saída de resultados
ns <- s + (s * 25/100)
escreva("Novo Salário: ",ns)

fimalgoritmo
